insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66611, 8, NULL, '1', 'Computer Application', 1, 100, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66712, 10, NULL, '2', 'Electrical Engineering Fundamentals', 1, 200, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (65911, 10, NULL, '3', 'Mathematics‐1', 1, 200, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (65912, 10, NULL, '4', 'Physics‐1', 1, 200, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (65711, 10, NULL, '5', 'Bangla', 1, 200, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (65712, 4, NULL, '6', 'English', 1, 100, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (65812, 4, NULL, '7', 'PhysicalEducation', 1, 50, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66621, 8, NULL, '8', 'Database Application', 1, 100, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66622, 8, NULL, '9', 'IT support System-I', 1, 100, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66623, 8, NULL, '10', 'Graphics Design-I', 1, 100, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66823, 10, NULL, '11', 'Analog Electronics', 1, 200, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (65921, 10, NULL, '12', 'Mathematics-2', 1, 200, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (65922, 10, NULL, '13', 'Physics-2', 1, 200, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (65722, 6, NULL, '14', 'Communicative English', 1, 100, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66631, 8, NULL, '15', 'Programming Essentials', 1, 150, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66632, 8, NULL, '16', 'Web Design', 1, 150, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66633, 8, NULL, '17', 'Graphics design‐II', 1, 100, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66634, 8, NULL, '18', 'IT support System‐II', 1, 100, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (65931, 10, NULL, '19', 'Mathematics‐3', 1, 200, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (65913, 10, NULL, '20', 'Chemistry', 1, 200, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (65811, 6, NULL, '21', 'Social Science', 1, 150, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66641, 8, NULL, '22', 'Object Oriented Programming', 1, 150, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66642, 8, NULL, '23', 'Data Structure & Algorithm', 1, 150, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66643, 8, NULL, '24', 'Web Development', 1, 100, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66644, 12, NULL, '25', 'Data Communication System', 1, 200, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66645, 10, NULL, '26', 'Computer Peripherals', 1, 150, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66842, 10, NULL, '27', 'Principle of Digital Electronics', 1, 200, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (65841, 4, NULL, '28', 'BusinessOrganization', 1, 100, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66651, 8, NULL, '29', 'Programming in Java', 1, 150, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66652, 8, NULL, '30', 'Operating Systems application', 1, 150, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66653, 10, NULL, '31', 'Surveillance Security System', 1, 150, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66654, 8, NULL, '32', 'Web Development Project', 1, 100, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66655, 10, NULL, '33', 'Sequential Logic System', 1, 200, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66656, 8, NULL, '34', 'PCB Design and Circuit Making', 1, 100, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (65851, 8, NULL, '35', 'Accounting', 1, 150, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66661, 12, NULL, '40', 'Principals of Software Engineering', 1, 200, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66662, 8, NULL, '41', 'Microprocessor & Interfacing', 1, 150, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66663, 8, NULL, '42', 'Microcontroller Application', 1, 100, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66664, 8, NULL, '43', 'Database Management System', 1, 150, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66660, 8, NULL, '44', 'Optional Subject ‐1', 1, 150, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (64054, 4, NULL, '45', 'Environmental Studies', 1, 100, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (65852, 4, NULL, '46', 'Industrial Management', 1, 100, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66671, 8, NULL, '47', 'System Analysis & Design', 1, 150, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66672, 12, NULL, '48', 'NetworkAdministration&Services', 1, 200, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66673, 8, NULL, '49', 'Apps Development Project', 1, 100, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66674, 12, NULL, '50', 'E‐Commerce & CMS', 1, 200, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66675, 6, NULL, '51', 'Cyber Security & Ethics', 1, 100, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (66670, 8, NULL, '52', 'Optional Subject‐II', 1, 150, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (65853, 4, NULL, '53', 'Innovation & Entrepreneurship', 1, 100, NULL);
insert into `subject` (`code`, `cradit`, `created_at`, `id`, `name`, `status`, `total`, `updated_at`) values (0, 6, NULL, '54', 'Industrial Attachment', 1, 300, NULL);
